controllers:
  seerr:
    containers:
      app:
        image:
          repository: ghcr.io/seerr-team/seerr
          tag: latest
        env:
          TZ: "America/Edmonton"
          LOG_LEVEL: "info"
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

defaultPodOptions:
  securityContext:
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch

service:
  app:
    controller: seerr
    type: NodePort
    ports:
      http:
        port: 5055

ingress:
  app:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    hosts:
      - host: seerr.snekxs.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - seerr.snekxs.xyz
        secretName: seerr-tls

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 2Gi
    storageClass: local-path
    globalMounts:
      - path: /app/config
