controllers:
  couchdb:
    containers:
      app:
        image:
          repository: couchdb
          tag: "3"
        env:
          COUCHDB_USER:
            valueFrom:
              secretKeyRef:
                name: couchdb-secret
                key: COUCHDB_USER
          COUCHDB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: couchdb-secret
                key: COUCHDB_PASSWORD
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

service:
  app:
    controller: couchdb
    type: NodePort
    ports:
      http:
        port: 5984

ingress:
  app:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: couchdb.snekxs.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - couchdb.snekxs.xyz
        secretName: couchdb-tls

persistence:
  data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: local-path
    globalMounts:
      - path: /opt/couchdb/data
