controllers:
  home-assistant:
    pod:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    containers:
      app:
        image:
          repository: ghcr.io/home-assistant/home-assistant
          tag: stable
        env:
          TZ: "America/Edmonton"
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        securityContext:
          privileged: true
      matter-server:
        image:
          repository: ghcr.io/home-assistant-libs/python-matter-server
          tag: stable
        args:
          - --storage-path
          - /data
          - --paa-trust-store-path
          - /data/credentials
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

configMaps:
  config:
    data:
      configuration.yaml: |
        default_config:
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            - 10.0.0.0/8
            - 172.16.0.0/12
            - 192.168.0.0/16

service:
  app:
    controller: home-assistant
    type: NodePort
    ports:
      http:
        port: 8123

ingress:
  app:
    className: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-cloudflare
    hosts:
      - host: ha.snekxs.xyz
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - ha.snekxs.xyz
        secretName: home-assistant-tls

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 5Gi
    storageClass: local-path
    globalMounts:
      - path: /config
  ha-config:
    type: configMap
    name: home-assistant
    globalMounts:
      - path: /config/configuration.yaml
        subPath: configuration.yaml
  matter-data:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: local-path
    advancedMounts:
      home-assistant:
        matter-server:
          - path: /data
