apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zipline
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/snekxs/homelab
    targetRevision: HEAD
    path: apps/zipline
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: zipline
  syncPolicy:
    automated:
      prune: true
      selfHeal: true